<?php

namespace App\Support;

class LaborCatalogDefaults
{
    public static function hourlyRate(): float
    {
        return 3000;
    }

    /**
     * @return list<array{name: string, items: list<array{name: string, hours: float}>}>
     */
    public static function catalog(): array
    {
        return [
            [
                'name' => 'Brakes',
                'items' => [
                    ['name' => 'Front brake pads replacement', 'hours' => 1.0],
                    ['name' => 'Rear brake pads replacement', 'hours' => 1.0],
                    ['name' => 'Front brake discs/rotors replacement', 'hours' => 1.5],
                    ['name' => 'Rear brake discs/rotors replacement', 'hours' => 1.5],
                    ['name' => 'Front brake pads + discs replacement', 'hours' => 2.0],
                    ['name' => 'Rear brake pads + discs replacement', 'hours' => 2.0],
                    ['name' => 'Brake fluid flush / complete system bleed', 'hours' => 1.0],
                    ['name' => 'Brake fluid top-up', 'hours' => 0.25],
                    ['name' => 'Front caliper cleaning, greasing & lubrication', 'hours' => 1.0],
                    ['name' => 'Rear caliper cleaning, greasing & lubrication', 'hours' => 1.0],
                    ['name' => 'Front caliper overhaul / rebuild', 'hours' => 2.0],
                    ['name' => 'Rear caliper overhaul / rebuild', 'hours' => 2.0],
                    ['name' => 'Front caliper replacement', 'hours' => 1.5],
                    ['name' => 'Rear caliper replacement', 'hours' => 1.5],
                    ['name' => 'Brake shoe adjustment (rear drum)', 'hours' => 0.75],
                    ['name' => 'Rear drum brake shoes replacement', 'hours' => 1.5],
                    ['name' => 'Rear drum cleaning & adjustment', 'hours' => 1.0],
                    ['name' => 'Handbrake / parking brake adjustment', 'hours' => 0.5],
                    ['name' => 'Handbrake cable replacement', 'hours' => 1.5],
                    ['name' => 'Handbrake lever mechanism repair', 'hours' => 1.0],
                    ['name' => 'ABS sensor replacement (front)', 'hours' => 0.75],
                    ['name' => 'ABS sensor replacement (rear)', 'hours' => 0.75],
                    ['name' => 'ABS module diagnosis & repair', 'hours' => 2.0],
                    ['name' => 'Brake master cylinder replacement', 'hours' => 2.0],
                    ['name' => 'Brake booster / vacuum servo replacement', 'hours' => 2.5],
                    ['name' => 'Brake line / pipe replacement', 'hours' => 1.5],
                    ['name' => 'Flexible brake hose replacement', 'hours' => 0.75],
                    ['name' => 'Brake proportioning valve replacement', 'hours' => 1.5],
                    ['name' => 'Wheel speed sensor replacement', 'hours' => 0.75],
                    ['name' => 'Brake system pressure test', 'hours' => 0.5],
                    ['name' => 'Brake warning light diagnosis', 'hours' => 0.75],
                ],
            ],
            [
                'name' => 'Engine Mechanical',
                'items' => [
                    ['name' => 'Engine oil & filter change', 'hours' => 0.5],
                    ['name' => 'Engine oil change only', 'hours' => 0.35],
                    ['name' => 'Spark plugs replacement', 'hours' => 0.75],
                    ['name' => 'Ignition coil replacement', 'hours' => 0.75],
                    ['name' => 'Timing belt replacement', 'hours' => 4.0],
                    ['name' => 'Timing chain replacement / tensioner', 'hours' => 6.0],
                    ['name' => 'Water pump replacement', 'hours' => 2.5],
                    ['name' => 'Thermostat replacement', 'hours' => 1.0],
                    ['name' => 'Radiator replacement', 'hours' => 2.0],
                    ['name' => 'Radiator hose replacement (upper/lower)', 'hours' => 0.75],
                    ['name' => 'Coolant flush & refill', 'hours' => 1.0],
                    ['name' => 'Cylinder head gasket replacement', 'hours' => 8.0],
                    ['name' => 'Engine mount replacement (left/right/front/rear)', 'hours' => 1.5],
                    ['name' => 'Valve cover gasket replacement', 'hours' => 1.5],
                    ['name' => 'Oil pan gasket replacement', 'hours' => 3.0],
                    ['name' => 'Crankshaft seal replacement (front/rear)', 'hours' => 3.0],
                    ['name' => 'Camshaft seal replacement', 'hours' => 2.0],
                    ['name' => 'PCV valve replacement', 'hours' => 0.5],
                    ['name' => 'Intake manifold gasket replacement', 'hours' => 2.5],
                    ['name' => 'Exhaust manifold gasket replacement', 'hours' => 2.0],
                    ['name' => 'Engine compression test', 'hours' => 1.0],
                    ['name' => 'Leak-down test', 'hours' => 1.0],
                    ['name' => 'Engine diagnostic (check engine light)', 'hours' => 1.0],
                    ['name' => 'Fuel injector cleaning', 'hours' => 1.0],
                    ['name' => 'Fuel injector replacement', 'hours' => 2.0],
                    ['name' => 'Throttle body cleaning', 'hours' => 0.75],
                    ['name' => 'Throttle body replacement', 'hours' => 1.5],
                    ['name' => 'Mass air flow (MAF) sensor replacement', 'hours' => 0.5],
                    ['name' => 'Oxygen / lambda sensor replacement', 'hours' => 0.75],
                    ['name' => 'Knock sensor replacement', 'hours' => 1.5],
                    ['name' => 'Crankshaft position sensor replacement', 'hours' => 1.0],
                    ['name' => 'Camshaft position sensor replacement', 'hours' => 1.0],
                    ['name' => 'Engine control module (ECM/PCM) diagnosis', 'hours' => 1.5],
                ],
            ],
            [
                'name' => 'Transmission & Clutch',
                'items' => [
                    ['name' => 'Manual transmission oil change', 'hours' => 0.75],
                    ['name' => 'Automatic transmission fluid & filter change', 'hours' => 1.5],
                    ['name' => 'Clutch kit replacement (disc, pressure plate, release bearing)', 'hours' => 5.0],
                    ['name' => 'Dual mass flywheel replacement', 'hours' => 5.5],
                    ['name' => 'Clutch master cylinder replacement', 'hours' => 1.5],
                    ['name' => 'Clutch slave cylinder replacement', 'hours' => 1.5],
                    ['name' => 'Clutch cable adjustment / replacement', 'hours' => 0.75],
                    ['name' => 'Gearbox mount replacement', 'hours' => 1.5],
                    ['name' => 'Differential oil change', 'hours' => 0.75],
                    ['name' => 'Differential seal replacement', 'hours' => 2.0],
                    ['name' => 'Transfer case oil change (4WD)', 'hours' => 0.75],
                    ['name' => 'CV joint / driveshaft replacement', 'hours' => 2.0],
                    ['name' => 'Propeller shaft / center bearing replacement', 'hours' => 2.0],
                    ['name' => 'Automatic transmission diagnosis', 'hours' => 1.5],
                    ['name' => 'Torque converter replacement', 'hours' => 6.0],
                    ['name' => 'Gear selector cable adjustment / replacement', 'hours' => 1.0],
                ],
            ],
            [
                'name' => 'Suspension & Steering',
                'items' => [
                    ['name' => 'Front shock absorber / strut replacement', 'hours' => 1.5],
                    ['name' => 'Rear shock absorber replacement', 'hours' => 1.0],
                    ['name' => 'Front coil spring replacement', 'hours' => 1.5],
                    ['name' => 'Rear coil spring replacement', 'hours' => 1.5],
                    ['name' => 'Front lower control arm replacement', 'hours' => 1.5],
                    ['name' => 'Front upper control arm replacement', 'hours' => 1.5],
                    ['name' => 'Ball joint replacement', 'hours' => 1.0],
                    ['name' => 'Tie rod end replacement', 'hours' => 0.75],
                    ['name' => 'Steering rack replacement', 'hours' => 3.5],
                    ['name' => 'Power steering fluid flush', 'hours' => 0.75],
                    ['name' => 'Power steering pump replacement', 'hours' => 2.0],
                    ['name' => 'Power steering hose replacement', 'hours' => 1.0],
                    ['name' => 'Wheel alignment (2-wheel / 4-wheel)', 'hours' => 1.0],
                    ['name' => 'Front wheel bearing replacement', 'hours' => 1.5],
                    ['name' => 'Rear wheel bearing replacement', 'hours' => 1.5],
                    ['name' => 'Sway bar / anti-roll bar link replacement', 'hours' => 0.5],
                    ['name' => 'Sway bar bush replacement', 'hours' => 0.75],
                    ['name' => 'Subframe bush replacement', 'hours' => 3.0],
                    ['name' => 'Steering column intermediate shaft replacement', 'hours' => 1.5],
                    ['name' => 'Suspension diagnosis & inspection', 'hours' => 0.75],
                ],
            ],
            [
                'name' => 'Exhaust System',
                'items' => [
                    ['name' => 'Front exhaust pipe replacement', 'hours' => 1.0],
                    ['name' => 'Catalytic converter replacement', 'hours' => 1.5],
                    ['name' => 'Intermediate exhaust pipe replacement', 'hours' => 1.0],
                    ['name' => 'Rear muffler / silencer replacement', 'hours' => 0.75],
                    ['name' => 'Exhaust manifold replacement', 'hours' => 2.5],
                    ['name' => 'Exhaust gasket replacement', 'hours' => 1.0],
                    ['name' => 'Oxygen sensor (pre-cat / post-cat) replacement', 'hours' => 0.75],
                    ['name' => 'Exhaust leak repair (welding / clamp)', 'hours' => 1.0],
                    ['name' => 'Diesel particulate filter (DPF) cleaning', 'hours' => 2.0],
                    ['name' => 'DPF replacement', 'hours' => 2.5],
                    ['name' => 'EGR valve cleaning', 'hours' => 1.0],
                    ['name' => 'EGR valve replacement', 'hours' => 1.5],
                    ['name' => 'Exhaust flex pipe replacement', 'hours' => 1.0],
                ],
            ],
            [
                'name' => 'Electrical & Battery',
                'items' => [
                    ['name' => 'Battery replacement', 'hours' => 0.35],
                    ['name' => 'Battery terminal cleaning & protection', 'hours' => 0.25],
                    ['name' => 'Alternator replacement', 'hours' => 1.5],
                    ['name' => 'Starter motor replacement', 'hours' => 1.5],
                    ['name' => 'Alternator belt replacement', 'hours' => 0.5],
                    ['name' => 'Battery charging system test', 'hours' => 0.5],
                    ['name' => 'Starter circuit diagnosis', 'hours' => 0.75],
                    ['name' => 'Fuse replacement', 'hours' => 0.25],
                    ['name' => 'Relay replacement', 'hours' => 0.35],
                    ['name' => 'Wiring harness repair', 'hours' => 2.0],
                    ['name' => 'Headlight bulb replacement', 'hours' => 0.35],
                    ['name' => 'Tail light / brake light bulb replacement', 'hours' => 0.25],
                    ['name' => 'Indicator / turn signal bulb replacement', 'hours' => 0.25],
                    ['name' => 'Interior light bulb replacement', 'hours' => 0.25],
                    ['name' => 'Headlight assembly replacement', 'hours' => 1.0],
                    ['name' => 'Tail light assembly replacement', 'hours' => 0.75],
                    ['name' => 'Window regulator (power window) replacement', 'hours' => 1.5],
                    ['name' => 'Central locking actuator replacement', 'hours' => 1.0],
                    ['name' => 'Key fob battery replacement / programming', 'hours' => 0.5],
                    ['name' => 'Immobilizer / key programming', 'hours' => 1.0],
                    ['name' => 'ECU / module coding & programming', 'hours' => 1.5],
                    ['name' => 'Diagnostic scan (full system)', 'hours' => 0.75],
                    ['name' => 'Parasitic drain test', 'hours' => 1.0],
                ],
            ],
            [
                'name' => 'Air Conditioning & Heating',
                'items' => [
                    ['name' => 'A/C performance test & diagnosis', 'hours' => 0.75],
                    ['name' => 'A/C refrigerant recharge (R134a / R1234yf)', 'hours' => 1.0],
                    ['name' => 'A/C compressor replacement', 'hours' => 3.0],
                    ['name' => 'A/C condenser replacement', 'hours' => 2.0],
                    ['name' => 'A/C evaporator replacement', 'hours' => 5.0],
                    ['name' => 'A/C expansion valve / orifice tube replacement', 'hours' => 1.5],
                    ['name' => 'A/C receiver-drier / accumulator replacement', 'hours' => 1.0],
                    ['name' => 'A/C pressure switch replacement', 'hours' => 0.75],
                    ['name' => 'Cabin / pollen filter replacement', 'hours' => 0.35],
                    ['name' => 'Heater core replacement', 'hours' => 5.0],
                    ['name' => 'Heater blower motor replacement', 'hours' => 1.5],
                    ['name' => 'Climate control panel diagnosis / replacement', 'hours' => 1.5],
                    ['name' => 'A/C belt replacement', 'hours' => 0.5],
                ],
            ],
            [
                'name' => 'Cooling System',
                'items' => [
                    ['name' => 'Coolant leak diagnosis', 'hours' => 0.75],
                    ['name' => 'Radiator pressure test', 'hours' => 0.5],
                    ['name' => 'Water pump replacement', 'hours' => 2.5],
                    ['name' => 'Thermostat housing replacement', 'hours' => 1.25],
                    ['name' => 'Coolant temperature sensor replacement', 'hours' => 0.5],
                    ['name' => 'Radiator fan motor / clutch replacement', 'hours' => 1.5],
                    ['name' => 'Electric cooling fan replacement', 'hours' => 1.0],
                    ['name' => 'Coolant reservoir / expansion tank replacement', 'hours' => 0.5],
                    ['name' => 'Heater hose replacement', 'hours' => 0.75],
                    ['name' => 'Cylinder head temperature sensor replacement', 'hours' => 0.75],
                ],
            ],
            [
                'name' => 'Fuel System',
                'items' => [
                    ['name' => 'Fuel filter replacement', 'hours' => 0.5],
                    ['name' => 'Fuel pump replacement (in-tank / external)', 'hours' => 2.5],
                    ['name' => 'Fuel pressure regulator replacement', 'hours' => 1.0],
                    ['name' => 'Fuel tank sender unit replacement', 'hours' => 2.0],
                    ['name' => 'Fuel rail replacement', 'hours' => 1.5],
                    ['name' => 'Fuel line repair / replacement', 'hours' => 1.5],
                    ['name' => 'Diesel fuel system bleeding', 'hours' => 0.75],
                    ['name' => 'Injector pump diagnosis (diesel)', 'hours' => 1.5],
                    ['name' => 'High-pressure fuel pump replacement (GDI / diesel)', 'hours' => 3.5],
                ],
            ],
            [
                'name' => 'Body & Interior',
                'items' => [
                    ['name' => 'Windscreen / windshield replacement', 'hours' => 2.0],
                    ['name' => 'Windscreen chip repair', 'hours' => 0.5],
                    ['name' => 'Side window replacement', 'hours' => 1.5],
                    ['name' => 'Door lock mechanism repair', 'hours' => 1.0],
                    ['name' => 'Door handle replacement (interior / exterior)', 'hours' => 0.75],
                    ['name' => 'Mirror glass replacement', 'hours' => 0.35],
                    ['name' => 'Side mirror assembly replacement', 'hours' => 0.75],
                    ['name' => 'Bumper repair / replacement (front / rear)', 'hours' => 2.0],
                    ['name' => 'Bonnet / hood latch adjustment', 'hours' => 0.5],
                    ['name' => 'Tailgate / boot latch repair', 'hours' => 0.75],
                    ['name' => 'Seat belt replacement', 'hours' => 1.0],
                    ['name' => 'Seat adjustment motor repair', 'hours' => 1.5],
                    ['name' => 'Dashboard warning light diagnosis', 'hours' => 0.75],
                    ['name' => 'Interior trim repair / replacement', 'hours' => 1.0],
                ],
            ],
            [
                'name' => 'Tyres & Wheels',
                'items' => [
                    ['name' => 'Tyre fitting (per tyre)', 'hours' => 0.25],
                    ['name' => 'Tyre balancing (per wheel)', 'hours' => 0.25],
                    ['name' => 'Wheel alignment check', 'hours' => 0.5],
                    ['name' => 'Puncture repair', 'hours' => 0.35],
                    ['name' => 'Tyre pressure monitoring system (TPMS) sensor replacement', 'hours' => 0.5],
                    ['name' => 'TPMS relearn / programming', 'hours' => 0.35],
                    ['name' => 'Alloy wheel refurbishment (cosmetic)', 'hours' => 2.0],
                    ['name' => 'Wheel nut / stud replacement', 'hours' => 0.5],
                    ['name' => 'Spare wheel carrier repair', 'hours' => 1.0],
                ],
            ],
            [
                'name' => 'Routine Service & Inspection',
                'items' => [
                    ['name' => 'Full service (oil, filters, inspection)', 'hours' => 1.5],
                    ['name' => 'Interim / intermediate service', 'hours' => 1.0],
                    ['name' => 'Major service', 'hours' => 2.5],
                    ['name' => 'Pre-purchase inspection', 'hours' => 1.5],
                    ['name' => 'MOT / annual inspection preparation', 'hours' => 1.0],
                    ['name' => 'Brake & suspension safety inspection', 'hours' => 0.75],
                    ['name' => 'Underbody inspection & rust treatment', 'hours' => 1.5],
                    ['name' => 'Vehicle health check / multi-point inspection', 'hours' => 1.0],
                    ['name' => 'Timing belt inspection', 'hours' => 0.75],
                    ['name' => 'Cambelt / chain condition report', 'hours' => 0.75],
                ],
            ],
            [
                'name' => 'Hybrid / Electric Specific',
                'items' => [
                    ['name' => 'High-voltage battery diagnosis', 'hours' => 1.5],
                    ['name' => 'Hybrid system coolant change', 'hours' => 1.0],
                    ['name' => 'Inverter coolant pump replacement', 'hours' => 2.0],
                    ['name' => 'Hybrid battery cooling fan replacement', 'hours' => 1.5],
                    ['name' => 'Regenerative braking system check', 'hours' => 1.0],
                    ['name' => 'EV charging port diagnosis', 'hours' => 1.0],
                    ['name' => '12V auxiliary battery replacement (hybrid/EV)', 'hours' => 0.5],
                ],
            ],
        ];
    }
}
